document.addEventListener('DOMContentLoaded',function(){
    // animation du décors
    document.getElementById('triangle').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('triangle1').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle1').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('triangle2').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle2').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('triangle3').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle3').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('triangle4').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle4').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('triangle5').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('triangle5').style.animation = 'stretch 0.8s';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('circle').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle5').style.animation = '';
    });
    document.getElementById('circle').addEventListener('mouseover' , function() {
        console.log('vous êtes dans la console');
        document.getElementById('circle').style.animation = 'stretch 0.8s';
        document.getElementById('triangle').style.animation = '';
        document.getElementById('triangle1').style.animation = '';
        document.getElementById('triangle2').style.animation = '';
        document.getElementById('triangle3').style.animation = '';
        document.getElementById('triangle4').style.animation = '';
        document.getElementById('triangle5').style.animation = '';
        document.getElementById('circle1').style.animation = '';
        document.getElementById('circle2').style.animation = '';
        document.getElementById('circle3').style.animation = '';
        document.getElementById('circle4').style.animation = '';
        document.getElementById('circle55').style.animation = '';
       });
document.getElementById('circle1').addEventListener('mouseover' , function() {
    console.log('vous êtes dans la console');
    document.getElementById('circle1').style.animation = 'stretch 0.8s';
    document.getElementById('triangle').style.animation = '';
    document.getElementById('triangle1').style.animation = '';
    document.getElementById('triangle2').style.animation = '';
    document.getElementById('triangle3').style.animation = '';
    document.getElementById('triangle4').style.animation = '';
    document.getElementById('triangle5').style.animation = '';
    document.getElementById('circle').style.animation = '';
    document.getElementById('circle2').style.animation = '';
    document.getElementById('circle3').style.animation = '';
    document.getElementById('circle4').style.animation = '';
    document.getElementById('circle5').style.animation = '';
});
document.getElementById('circle2').addEventListener('mouseover' , function() {
    console.log('vous êtes dans la console');
    document.getElementById('circle2').style.animation = 'stretch 0.8s';
    document.getElementById('triangle').style.animation = '';
    document.getElementById('triangle1').style.animation = '';
    document.getElementById('triangle2').style.animation = '';
    document.getElementById('triangle3').style.animation = '';
    document.getElementById('triangle4').style.animation = '';
    document.getElementById('triangle5').style.animation = '';
    document.getElementById('circle').style.animation = '';
    document.getElementById('circle1').style.animation = '';
    document.getElementById('circle3').style.animation = '';
    document.getElementById('circle4').style.animation = '';
    document.getElementById('circle5').style.animation = '';
});
document.getElementById('circle3').addEventListener('mouseover' , function() {
    console.log('vous êtes dans la console');
    document.getElementById('circle3').style.animation = 'stretch 0.8s';
    document.getElementById('triangle').style.animation = '';
    document.getElementById('triangle1').style.animation = '';
    document.getElementById('triangle2').style.animation = '';
    document.getElementById('triangle3').style.animation = '';
    document.getElementById('triangle4').style.animation = '';
    document.getElementById('triangle5').style.animation = '';
    document.getElementById('circle').style.animation = '';
    document.getElementById('circle2').style.animation = '';
    document.getElementById('circle1').style.animation = '';
    document.getElementById('circle4').style.animation = '';
    document.getElementById('circle5').style.animation = '';
});
document.getElementById('circle4').addEventListener('mouseover' , function() {
    console.log('vous êtes dans la console');
    document.getElementById('circle4').style.animation = 'stretch 0.8s';
    document.getElementById('triangle').style.animation = '';
    document.getElementById('triangle1').style.animation = '';
    document.getElementById('triangle2').style.animation = '';
    document.getElementById('triangle3').style.animation = '';
    document.getElementById('triangle4').style.animation = '';
    document.getElementById('triangle5').style.animation = '';
    document.getElementById('circle').style.animation = '';
    document.getElementById('circle2').style.animation = '';
    document.getElementById('circle3').style.animation = '';
    document.getElementById('circle1').style.animation = '';
    document.getElementById('circle5').style.animation = '';
});
document.getElementById('circle5').addEventListener('mouseover' , function() {
    console.log('vous êtes dans la console');
    document.getElementById('circle5').style.animation = 'stretch 0.8s';
    document.getElementById('triangle').style.animation = '';
    document.getElementById('triangle1').style.animation = '';
    document.getElementById('triangle2').style.animation = '';
    document.getElementById('triangle3').style.animation = '';
    document.getElementById('triangle4').style.animation = '';
    document.getElementById('triangle5').style.animation = '';
    document.getElementById('circle').style.animation = '';
    document.getElementById('circle2').style.animation = '';
    document.getElementById('circle3').style.animation = '';
    document.getElementById('circle4').style.animation = '';
    document.getElementById('circle1').style.animation = '';
});
/////////////////////////////////////////////////// animation du décors
})